routes/admin.php
<?php
Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']],
    function () {
        Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
            Route::get('index', 'DashboardController@index')->name('admin.index');
//            Users Routes
            Route::resource('users', 'UserController')->except(['show']);
//            Categories Routes
            Route::resource('categories', 'CategoryController')->except(['show']);

//            products Routes
            Route::resource('products', 'ProductController')->except(['show']);

//            clients Routes
            Route::resource('clients', 'ClientController')->except(['show']);


//            clients Orders Routes
            Route::resource('clients.orders', 'Client\OrderController')->except(['show']);


            // Order Routes
            Route::resource('orders', 'OrderController')->except(['show']);

//            To Show Orders Products
            Route::get('/orders/{order}/products' , 'OrderController@products')->name('orders.products');


        });
    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.index');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
   protected $guarded = [];

   protected $casts = [
       'phone' => 'array'
   ];

    public function orders()
    {
        return $this->hasMany(Order::class);

    }

    public function getNameAttribute($value)
    {
        return ucfirst($value);
    }






}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware(['permission:read_categories'])->only('index');
        $this->middleware(['permission:create_categories'])->only('create');
        $this->middleware(['permission:update_categories'])->only('edit');
        $this->middleware(['permission:delete_categories'])->only('destroy');
    }

    public function index(Request $request)
    {
        $categories = Category::when($request->search,
            function ($query) use ($request) {
                return $query->whereTranslationLike('name', 'like', '%' . $request->search . '%');
            })->latest()->paginate(5);
        return view('dashboard.categories.index', compact('categories'));
    }


    public function create()
    {
        return view('dashboard.categories.create');
    }


    public function store(Request $request)
    {
        $rules = [];

        foreach (config('translatable.locales') as $locale) {
            $rules += [$locale . '.name' => ['required', Rule::unique('category_translations', 'name')]];
        }//end of for each

        $request->validate($rules);

        Category::create($request->all());
        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('categories.index');


    } // End Of Store


    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', compact('category'));
    }


    public function update(Request $request, Category $category)
    {
        $rules = [];

        foreach (config('translatable.locales') as $locale) {

            $rules += [$locale . '.name' => ['required', Rule::unique('category_translations', 'name')->ignore($category->id, 'category_id')]];

        }//end of for each

        $request->validate($rules);

        $category->update($request->all());
        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('categories.index');

    }


    public function destroy(Category $category)
    {
        $category->delete();

        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('categories.index');
    }
}

app/Http/Controllers/Dashboard/Client/OrderController.php
<?php

namespace App\Http\Controllers\Dashboard\Client;

use App\Category;
use App\Client;
use App\Http\Controllers\Controller;
use App\order;
use App\Product;
use Illuminate\Http\Request;

class OrderController extends Controller
{

    public function create(Client $client)
    {
        $categories = Category::with('products')->get();
        $orders = $client->orders()->with('products')->paginate(5);
        return view('dashboard.clients.orders.create', compact('client', 'orders', 'categories'));
    }

    public function store(Request $request, Client $client)
    {

        $request->validate([
            'products' => 'required|array',
        ]);

        $this->attach_order($request, $client);

        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('orders.index');

    }


    public function edit(Client $client, order $order)
    {
        $categories = Category::with('products')->get();
        $orders = $client->orders()->with('products')->paginate(5);
        return view('dashboard.clients.orders.edit', compact('client', 'order', 'categories', 'orders'));
    }


    public function update(Request $request, Client $client, order $order)
    {
        $request->validate([
            'products' => 'required|array',
        ]);

        $this->detach_order($order); // To Delete old order  and create a new One.
        $this->attach_order($request, $client); // Create A new order


        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('orders.index');


    }

    public function destroy(order $order)
    {
        //
    }


    private function attach_order($request, $client)
    {
        $order = $client->orders()->create([]);

        $order->products()->attach($request->products);

        $total_price = 0;

        foreach ($request->products as $id => $quantity) {

            $product = Product::FindOrFail($id);
            $total_price += $product->sale_price * $quantity['quantity'];

            $product->update([
                'stock' => $product->stock - $quantity['quantity']
            ]);

        }//end of foreach

        $order->update([
            'total_price' => $total_price
        ]);

    }//end of attach order


    private function detach_order($order)
    {
        foreach ($order->products as $product) {

            $product->update([
                'stock' => $product->stock + $product->pivot->quantity
            ]);

        }//end of for each

        $order->delete();

    }


}

app/Http/Controllers/Dashboard/ClientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{

    public function index(Request $request)
    {
        $clients = Client::when($request->search, function ($q) use ($request) {
            return $q->where('name', 'like', '%' . $request->search . '%')
                ->orWhere('phone', 'like', '%' . $request->search . '%')
                ->orWhere('address', 'like', '%' . $request->search . '%');

        })->latest()->paginate(5);

        return view('dashboard.clients.index', compact('clients'));

    }//end of index

    public function create()
    {
        return view('dashboard.clients.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required|array|min:1',
            'phone.0' => 'required',
            'address' => 'required',
        ]);

        $data = $request->all();
        $data['phone'] = array_filter($request->phone);

        Client::create($data);
        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('clients.index');
    }


    public function edit(client $client)
    {
        return view('dashboard.clients.edit', compact('client'));
    }


    public function update(Request $request, client $client)
    {

        $request->validate([
            'name' => 'required',
            'phone' => 'required|array|min:1',
            'phone.0' => 'required',
            'address' => 'required',
        ]);

        $data = $request->all();
        $data['phone'] = array_filter($request->phone);

        $client->update($data);
        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('clients.index');
    }

    public function destroy(client $client)
    {
        $client->delete();

        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('clients.index');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Category;
use App\Client;
use App\Order;
use App\Product;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
class DashboardController extends Controller
{
    public function index()
    {
        $categories_count = Category::count();
        $products_count = Product::count();
        $clients_count = Client::count();
        $users_count = User::whereRoleIs('admin')->count();

        $sales_data = Order::select(
            DB::raw('YEAR(created_at) as year'),
            DB::raw('MONTH(created_at) as month'),
            DB::raw('SUM(total_price) as sum')
        )->groupBy('month')->get();


        return view('dashboard.index', compact('categories_count', 'products_count', 'clients_count', 'users_count', 'sales_data'));

    }//end of index
}

app/Http/Controllers/Dashboard/OrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

// use App\Order;


class OrderController extends Controller
{

    public function __construct()
    {
        $this->middleware(['permission:read_orders'])->only('index');
        $this->middleware(['permission:create_orders'])->only('create');
        $this->middleware(['permission:update_orders'])->only('edit');
        $this->middleware(['permission:delete_orders'])->only('destroy');

    }

    public function index(Request $request)
    {

        $orders = Order::whereHas('client', function ($q) use ($request) {
            return $q->where('name', 'LIKE', '%' . $request->search . '%');

        })->paginate(5);

        return view('dashboard.orders.index', compact('orders'));
//        return view('dashboard.orders.index', compact('orders'));
    }

    public function products(Order $order)
    {
        $products = $order->products;

//        dd($products);
        return view('dashboard.orders._products', compact('order', 'products'));
    }


    public function destroy(Order $order)
    {
//        To Increase Ordered Quantity In this Product
        foreach ($order->products as $product) {
            $product->update([
                'stock' => $product->stock + $product->pivot->quantity
            ]);
        }// end foreach


        $order->delete();
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('orders.index');

    }


}

app/Http/Controllers/Dashboard/ProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Product;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class ProductController extends Controller
{

    public function index(Request $request)
    {
        $categories = Category::all();
        $products = Product::when($request->search, function ($q) use ($request) {

            return $q->whereTranslationLike('name', '%' . $request->search . '%');

        })->when($request->category_id, function ($q) use ($request) {

            return $q->where('category_id', $request->category_id);

        })->latest()->paginate(5);

        return view('dashboard.products.index', compact('categories', 'products'));
    }


    public function create()
    {
        $categories = Category::all();
        return view('dashboard.products.create', compact('categories'));
    }


    public function store(Request $request)
    {
        // Validation
        $rules = [
            'category_id' => 'required'
        ];
        foreach (config('translatable.locales') as $locale) {
            $rules += [$locale . '.name' => 'required|unique:product_translations,name'];
            $rules += [$locale . '.description' => 'required'];
        }//End Of Foreach
        $rules += [
            'purchase_price' => 'required',
            'sale_price' => 'required',
            'stock' => 'required',
        ];
        $request->validate($rules);
        // End Of Validation

        $data = $request->all();

        // Image
        if ($request->image) {
            Image::make($request->image)
                ->resize('300', null, function ($constraint) {
                    $constraint->aspectRatio();
                })->save(public_path('uploads/products_images/' . $request->image->hashName()));

            $data['image'] = $request->image->hashname();
        }
        Product::create($data);
        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('products.index');
    }



    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('dashboard.products.edit', compact('categories', 'product'));
    }


    public function update(Request $request, Product $product)
    {
        $rules = [
            'category_id' => 'required'
        ];
        foreach (config('translatable.locales') as $locale) {
            $rules += [$locale . '.name' => ['required', Rule::unique('product_translations', 'name')
                ->ignore($product->id, 'product_id')]];
            $rules += [$locale . '.description' => 'required'];
        }//End Of Foreach
        $rules += [
            'purchase_price' => 'required',
            'sale_price' => 'required',
            'stock' => 'required',
        ];
        $request->validate($rules);
        // End Of Validation

        $data = $request->all();

        if ($product->image != 'default.png')
        {
            Storage::disk('public_uploads')->delete('/products_images/'. $product->image);
        }
        // Image
        if ($request->image) {
            Image::make($request->image)
                ->resize('300', null, function ($constraint) {
                    $constraint->aspectRatio();
                })->save(public_path('uploads/products_images/' . $request->image->hashName()));

            $data['image'] = $request->image->hashname();
        }

        $product->update($data);
        session()->flash('success' , __('site.updated_successfully'));
        return redirect()->route('products.index');
    }


    public function destroy(Product $product)
    {
        if ($product->image != 'default.png')
        {
            Storage::disk('public_uploads')->delete('/products_images/'. $product->image);
        }

        $product->delete();
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('products.index');
    }
}

resources/views/dashboard/clients/create.blade.php
@extends('layouts.dashboard.app')
@section('title', trans('site.create'))
@section('content')

    <div class="content-wrapper">
        <section class="content-header">
            <h1>@lang('site.clients')</h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i> @lang('site.dashboard')</a>
                </li>
                <li><a href="{{ route('clients.index') }}"><i class=""></i>@lang('site.clients')</a></li>
                <li class="active">@lang('site.add')</li>
            </ol>
        </section>

        <section class="content">
            <div class="box box-primary">
                <div class="box-header"><h3 class="box-title">@lang('site.add')</h3></div>
                <div class="box-body">

                    @include('partials._errors')

                    <form action="{{ route('clients.store') }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('post') }}

                        <div class="form-group col-lg-12 tab-danger has-success">
                            <label>@lang('site.name')</label>
                            <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                        </div>

                        @for ($i = 0; $i < 2 ; $i++)

                            <div class="form-group col-lg-6 tab-danger has-warning">
                                <label>@lang('site.phone')</label>
                                <input type="text" name="phone[]" class="form-control">
                            </div>
                        @endfor


                        <div class="form-group col-lg-12 tab-danger has-success">
                            <label>@lang('site.address')</label>
                            <textarea name="address" class="form-control">{{ old('address') }}</textarea>
                        </div>

                        <div class="form-group col-lg-12">
                            <button type="submit" class="btn btn-primary"><i style="margin-left: 6px"
                                                                             class="fa fa-plus"></i>@lang('site.add')
                            </button>
                        </div>
                    </form>


                </div>
            </div>
        </section>
    </div>



@endsection

resources/views/dashboard/clients/edit.blade.php
@extends('layouts.dashboard.app')
@section('title', trans('site.edit'))
@section('content')

    <div class="content-wrapper">
        <section class="content-header">
            <h1>@lang('site.clients')</h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i> @lang('site.dashboard')</a>
                </li>
                <li><a href="{{ route('clients.index') }}"><i class=""></i>@lang('site.clients')</a></li>
                <li class="active">@lang('site.edit')</li>
            </ol>
        </section>

        <section class="content">
            <div class="box box-primary">
                <div class="box-header"><h3 class="box-title">@lang('site.edit')</h3></div>
                <div class="box-body">
                    @include('partials._errors')

                    <form action="{{ route('clients.update', $client->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('put') }}

                        <div class="form-group col-lg-12 tab-danger has-success">
                            <label>@lang('site.name')</label>
                            <input type="text" name="name" class="form-control" value="{{ $client->name }}">
                        </div>

                        @for ($i = 0; $i < 2; $i++)
                            <div class="form-group col-lg-6 tab-danger has-warning">
                                <label>@lang('site.phone')</label>
                                <input type="text" name="phone[]" value="{{ $client->phone[$i] ?? '' }}"
                                       class="form-control">
                            </div>
                        @endfor

                        <div class="form-group col-lg-12 tab-danger has-success">
                            <label>@lang('site.edit')</label>
                            <textarea name="address" class="form-control">{{ $client->address }}</textarea>
                        </div>

                        <div class="form-group col-lg-12">
                            <button type="submit" class="btn btn-primary"><i style="margin-left: 6px"
                                                                             class="fa fa-plus"></i>@lang('site.edit')
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </section>
    </div>



@endsection

resources/views/dashboard/clients/index.blade.php
@extends('layouts.dashboard.app')
@section('title', trans('site.clients'))

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>@lang('site.clients')</h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.index') }}">
                        <i class="fa fa-dashboard"></i>
                        @lang('site.dashboard')</a>
                </li>
                <li class="active">@lang('site.clients')</li>
            </ol>
        </section>
        <section class="content">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title" style="margin-bottom: 15px">@lang('site.clients')
                        <small>{{ $clients->total() }}</small></h3>

                    {{--                    <h3 class="box-title" style="margin-bottom: 15px">@lang('site.clients') <small>{{ $clients->total() }}</small></h3>--}}


                    <form action="{{ route('clients.index') }}" method="get">
                        <div class="row">
                            <div class="col-md-4">

                                @if(auth()->user()->hasPermission('read_clients'))
                                    <input type="text" name="search" class="form-control"
                                           placeholder="@lang('site.search')" value="{{ request()->search }}">
                                    {{--                                @else--}}
                                    {{--                                    <button class="btn btn-danger disabled">@lang('site.search')</button>--}}
                                @endif
                            </div>
                            <div class="col-md-4">
                                @if(auth()->user()->hasPermission('read_clients'))
                                    <button type="submit" class="btn btn-info">
                                        <i style="margin-left: 6px"
                                           class="fa fa-search"></i>@lang('site.search')
                                    </button>

                                @endif

                                @if(auth()->user()->hasPermission('create_clients'))

                                    <a href="{{ route('clients.create') }}" class="btn btn-primary"><i
                                            style="margin-left: 6px"
                                            class="fa fa-plus"></i>@lang('site.add')</a>
                                @else
                                    <button class="btn btn-danger disabled"> @lang('site.add')</button>
                                @endif
                            </div>
                        </div>
                    </form>
                </div><!-- end of box header -->
                <div class="box-body">
                    @if(auth()->user()->hasPermission('read_clients'))
                        @if ($clients->count() > 0)
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('site.name')</th>
                                    <th>@lang('site.phone')</th>
                                    <th>@lang('site.address')</th>
                                    <th>@lang('site.orders')</th>

                                    <th>@lang('site.action')</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach ($clients as $index=>$client)
                                    <tr>
                                        <td>{{ $index + 1 }}</td>
                                        <td>{{ $client->name }}</td>
                                        <td>{{ is_array($client->phone) ? implode($client->phone, '_') : $client->phone  }}</td>
                                        <td>{{ is_array(implode($client->phone, '_')) ?? $client->phone  }}</td>
                                        <td>{{ $client->address }}</td>
                                        <td>
                                            @if(auth()->user()->hasPermission('create_orders'))
                                                <a href="{{ route('clients.orders.create', $client->id ) }}"
                                                   class="btn btn-microsoft btn-sm">@lang('site.add_order')</a>
                                            @else
                                                <a href=""
                                                   class="btn btn-danger btn-sm disabled">@lang('site.add_order')</a>
                                            @endif
                                        </td>
                                        <td>

                                            @if(auth()->user()->hasPermission('update_clients'))
                                                <a href="{{ route('clients.edit', $client->id) }}"
                                                   class="btn btn-info btn-sm"><i
                                                        class="fa fa-edit"></i> @lang('site.edit')</a>
                                            @else
                                                <button class="btn btn-danger disabled">@lang('site.edit')</button>
                                            @endif

                                            @if(auth()->user()->hasPermission('delete_clients'))
                                                {{--------------------------------}}
                                                {{--Button Delete --}}
                                                <form action="{{ route('clients.destroy', $client->id) }}"
                                                      method="post"
                                                      style="display: inline-block">
                                                    {{ csrf_field() }}
                                                    {{ method_field('delete') }}
                                                    <button type="submit" class="btn btn-danger delete btn-sm"><i
                                                            class="fa fa-trash"></i> @lang('site.delete')</button>
                                                </form><!-- end of form -->
                                                {{--END Of Button Delete --}}
                                                {{--------------------------------}}

                                            @else
                                                <button class="btn btn-danger disabled"> @lang('site.delete')</button>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table><!-- end of table -->
                            {{ $clients->appends(request()->query())->links() }}
                        @else
                            <h2>@lang('site.no_data_found')</h2>
                        @endif
                    @else
                        <h2>@lang('site.no_data_found')</h2>
                    @endif
                </div><!-- end of box body -->
            </div><!-- end of box -->
        </section><!-- end of content -->
    </div><!-- end of content wrapper -->

@endsection